kind = "mobile"
previewPath = "/stock-mobile/"
title = "Stock Insight Mobile"
version = "1.0.0"
id = "artifacts/stock-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/stock-mobile/" ]
localPort = 21538

[services.development]
run = "pnpm --filter @workspace/stock-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/stock-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/stock-mobile", "run", "serve" ]

[services.env]
PORT = "21538"
BASE_PATH = "/stock-mobile/"
